In [1]:
import numpy as np

In [2]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
a.shape

(3, 5)

In [4]:
a.ndim

2

In [10]:
a.dtype

dtype('int32')

In [11]:
a.dtype.name

'int32'

In [14]:
a.itemsize

4

In [15]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [16]:
b.ndim

1

In [17]:
b.size

3

In [18]:
b.itemsize

4

In [19]:
b = np.array([1.2, 3.5, 5.1])
b

array([1.2, 3.5, 5.1])

In [20]:
b.dtype

dtype('float64')

In [21]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [22]:
a=np.zeros((3, 4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
a=np.ones((3, 4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
a = np.ones( (2,3,4), dtype=np.int16 )
a

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [27]:
a = np.empty( (2,3) ) 
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
a.ndim

2

In [29]:
a = np.arange( 10, 30, 5 )
a

array([10, 15, 20, 25])

In [30]:
a = np.arange( 0, 2, 0.3 ) 
a

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [31]:
a = np.linspace( 0, 2, 9 )
a

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [33]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [36]:
b = np.arange(100).reshape(25,4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]
 [40 41 42 43]
 [44 45 46 47]
 [48 49 50 51]
 [52 53 54 55]
 [56 57 58 59]
 [60 61 62 63]
 [64 65 66 67]
 [68 69 70 71]
 [72 73 74 75]
 [76 77 78 79]
 [80 81 82 83]
 [84 85 86 87]
 [88 89 90 91]
 [92 93 94 95]
 [96 97 98 99]]


In [37]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [38]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [40]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )

print(a)
print(b)

[20 30 40 50]
[0 1 2 3]


In [44]:
c = a-b
print(c)

[20 29 38 47]


In [45]:
c = b**2
print(c)

[0 1 4 9]


In [47]:
np.sin(a)

array([ 0.91294525, -0.98803162,  0.74511316, -0.26237485])

In [48]:
np.cos(b)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 ])

In [49]:
10*np.sin(c)

array([ 0.        ,  8.41470985, -7.56802495,  4.12118485])

In [50]:
c<4

array([ True,  True, False, False])

In [52]:
A = np.array( [[1,1],
                [0,1]] )
B = np.array( [[2,0],
               [3,4]] )
print(A)
print(B)

[[1 1]
 [0 1]]
[[2 0]
 [3 4]]


In [53]:
A*B

array([[2, 0],
       [0, 4]])

In [54]:
A@B

array([[5, 4],
       [3, 4]])

In [56]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [57]:
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [58]:
arr = np.diag([1,2,3,4,5,6,])
arr

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [59]:
rand_arr = np.random.randint(1,15, 3) 
rand_arr

array([ 5, 10,  4])

In [60]:
rand_arr = np.random.rand(4) 
rand_arr

array([0.2162279 , 0.37960616, 0.14222107, 0.99577319])

In [61]:
arr = np.random.randint(1,100,100)
arr = arr.reshape(4,5,5)
arr

array([[[38, 28, 73, 63, 84],
        [83, 45, 89, 56, 88],
        [50,  3, 20, 87, 18],
        [26, 98, 13, 18, 89],
        [58, 36, 91, 11, 61]],

       [[86, 64, 57, 88, 47],
        [24, 26, 46, 56, 73],
        [ 4, 35, 28, 78, 66],
        [49, 73, 80, 24, 30],
        [88, 89, 87, 25,  9]],

       [[42, 34, 92, 44, 75],
        [44, 73, 24, 49, 88],
        [85, 92, 40, 59, 62],
        [48, 63, 63, 58, 44],
        [18, 70, 76, 84, 15]],

       [[16, 54, 95, 47, 77],
        [48, 54, 71, 38, 71],
        [56,  5, 80, 84, 85],
        [13, 24, 75, 59, 27],
        [59, 92, 82, 63, 56]]])

In [63]:
d = np.exp(c*1j)
d

array([ 1.        +0.j        ,  0.54030231+0.84147098j,
       -0.65364362-0.7568025j , -0.91113026+0.41211849j])

In [64]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [66]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [67]:
b.min(axis=1)

array([0, 4, 8])

In [68]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

In [69]:
B = np.arange(3)
B

array([0, 1, 2])

In [70]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [71]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [72]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [76]:
a[:6:2] = 1000
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729],
      dtype=int32)

In [78]:
for i in a:
    print(i**(1/3.))

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [80]:
def f(x,y):
     return 10*x+y
    
b = np.fromfunction(f,(5,4), dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [82]:
b[2,3]

23

In [83]:
b[0:5, 1]

array([ 1, 11, 21, 31, 41])